name: Release

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '15'
      - name: Prepare
        run: |
          # Continue only if the latest commit is tagged
          [ "${GITHUB_REF#/refs/tags/}" = `git describe` ] || exit 1
          yarn && node scripts/action-helper.js
      - name: Build
        run: |
          yarn build
          mkdir -p $ASSETS_DIR $TEMP_DIR
          cd dist && zip -r ../$ASSETS_DIR/$ASSET_ZIP . && cd ..

          # Same as `yarn build:selfHosted` but only manifest is changed for now
          TARGET=selfHosted BETA=1 npx gulp manifest
          cd dist && zip -r ../$TEMP_DIR/$ASSET_SELF_HOSTED_ZIP . && cd ..
      - name: Sign AMO
        continue-on-error: true
        run: |
          node scripts/amo-sign
          hub release edit beta -p -m '' -a $TEMP_DIR/updates.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AMO_KEY: ${{ secrets.AMO_KEY }}
          AMO_SECRET: ${{ secrets.AMO_SECRET }}
      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -x
          params=("-m" "$RELEASE_NAME" "-m" "$RELEASE_NOTE")
          if [ "$PRERELEASE" = "true" ]; then
            params+=("-p")
          fi
          for asset in $ASSETS_DIR/*; do
            params+=("-a" "$asset")
          done
          hub release create "${params[@]}" v$VERSION
